-- =============================================================================
-- File:        sp_Employees.sql
-- Project:     Teamgle - Workforce Management Platform
-- Description: Stored Procedures for the Employee and Role module.
--
-- HOW TO USE:
--   UP   section  →  run once to create / update all procedures.
--   DOWN section  →  run to drop all procedures (rollback, at bottom of file).
--
-- NOTE: sp_GetManagerCompanyId is defined in sp_Customers.sql (shared).
-- NOTE: Uses XML splitting instead of STRING_SPLIT (compatible with SQL Server 2008+).
-- =============================================================================


-- =============================================================================
-- UP  —  Create (or replace) all stored procedures
-- =============================================================================


-- =============================================================================
-- Description:  sp_GetAllRoles
--               Returns global roles (no company) and company-specific roles.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_GetAllRoles
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT r.Roll_ID, r.Roll_name
    FROM   Roll r
    LEFT JOIN Roll_company rc ON r.Roll_ID = rc.roll_ID
    WHERE  rc.company_ID IS NULL OR rc.company_ID = @companyId
    ORDER BY r.Roll_name;
END;
GO


-- =============================================================================
-- Description:  sp_RoleNameExistsForCompany
--               Returns 1 if a role with the given name (case-insensitive)
--               already exists globally or for this company, 0 otherwise.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_RoleNameExistsForCompany
    @roleName  NVARCHAR(200),
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*)
    FROM   Roll r
    LEFT JOIN Roll_company rc ON r.Roll_ID = rc.roll_ID
    WHERE  LOWER(r.Roll_name) = LOWER(@roleName)
      AND  (rc.company_ID IS NULL OR rc.company_ID = @companyId);
END;
GO


-- =============================================================================
-- Description:  sp_CreateRole
--               Inserts a new company-specific role into Roll and Roll_company.
--               The GUID is generated by the caller (C# repository).
--               Runs inside a transaction.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateRole
    @rollId    NVARCHAR(36),
    @roleName  NVARCHAR(200),
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
    BEGIN TRY
        INSERT INTO Roll (Roll_ID, Roll_name)
        VALUES (@rollId, @roleName);

        INSERT INTO Roll_company (roll_ID, company_ID)
        VALUES (@rollId, @companyId);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO


-- =============================================================================
-- Description:  sp_ValidateRoleIds
--               Accepts a comma-separated list of role IDs and returns the
--               count that are valid (global or belonging to this company).
--               C# compares the count against the expected number to validate.
--               Uses XML splitting (compatible with SQL Server 2008+).
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_ValidateRoleIds
    @roleIdsCsv NVARCHAR(MAX),
    @companyId  NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*) AS MatchCount
    FROM   Roll r
    LEFT JOIN Roll_company rc ON r.Roll_ID = rc.roll_ID
    WHERE  r.Roll_ID IN (
        SELECT RTRIM(LTRIM(Split.a.value('.', 'NVARCHAR(36)')))
        FROM   (SELECT CAST('<X>' + REPLACE(@roleIdsCsv, ',', '</X><X>') + '</X>' AS XML)) AS A(xmlCol)
        CROSS APPLY A.xmlCol.nodes('/X') AS Split(a)
    )
    AND (rc.company_ID IS NULL OR rc.company_ID = @companyId);
END;
GO


-- =============================================================================
-- Description:  sp_EmailExists
--               Returns 1 if an email already exists in the User table, 0 otherwise.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_EmailExists
    @email NVARCHAR(200)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT COUNT(*)
    FROM   [User]
    WHERE  LOWER(email) = LOWER(@email);
END;
GO


-- =============================================================================
-- Description:  sp_GetEmployeesByCompany
--               Returns the core employee rows for a company (no roles).
--               Call sp_GetEmployeeRolesByCompany separately to load roles.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_GetEmployeesByCompany
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT u.user_ID,
           u.firstName,
           u.lastName,
           u.email,
           u.phoneNum,
           u.FBUID,
           e.cost_per_hour
    FROM   [User] u
    INNER JOIN Employee e ON u.user_ID = e.user_ID
    WHERE  u.company_ID = @companyId
    ORDER BY u.firstName, u.lastName;
END;
GO


-- =============================================================================
-- Description:  sp_GetEmployeeRolesByCompany
--               Returns all role assignments for every employee in a company.
--               Used together with sp_GetEmployeesByCompany to build the list.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_GetEmployeeRolesByCompany
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT er.employee_user_ID,
           r.Roll_name
    FROM   Employee_Roll er
    INNER JOIN Roll r ON er.roll_ID = r.Roll_ID
    INNER JOIN [User] u ON er.employee_user_ID = u.user_ID
    WHERE  u.company_ID = @companyId;
END;
GO


-- =============================================================================
-- Description:  sp_GetEmployeeById
--               Returns core columns for a single employee.
--               Returns empty result set if not found or wrong company.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_GetEmployeeById
    @userId    NVARCHAR(36),
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT u.user_ID,
           u.firstName,
           u.lastName,
           u.email,
           u.phoneNum,
           u.FBUID,
           e.cost_per_hour
    FROM   [User] u
    INNER JOIN Employee e ON u.user_ID = e.user_ID
    WHERE  u.user_ID    = @userId
      AND  u.company_ID = @companyId;
END;
GO


-- =============================================================================
-- Description:  sp_GetEmployeeRoles
--               Returns role ID + name for a single employee.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_GetEmployeeRoles
    @userId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT er.roll_ID,
           r.Roll_name
    FROM   Employee_Roll er
    INNER JOIN Roll r ON er.roll_ID = r.Roll_ID
    WHERE  er.employee_user_ID = @userId;
END;
GO


-- =============================================================================
-- Description:  sp_CreateEmployee
--               Inserts a new User + Employee row and their role assignments
--               inside a single transaction.
--               Roles are passed as a comma-separated string (@roleIdsCsv).
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateEmployee
    @userId      NVARCHAR(36),
    @email       NVARCHAR(200),
    @firstName   NVARCHAR(100),
    @lastName    NVARCHAR(100),
    @phoneNum    NVARCHAR(50)  = NULL,
    @costPerHour DECIMAL(18,2),
    @createdAt   DATETIME,
    @companyId   NVARCHAR(36),
    @roleIdsCsv  NVARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
    BEGIN TRY
        INSERT INTO [User]
            (user_ID, FBUID, email, firstName, lastName, phoneNum, company_ID, created_at)
        VALUES
            (@userId, NULL, @email, @firstName, @lastName, @phoneNum, @companyId, @createdAt);

        INSERT INTO Employee (user_ID, cost_per_hour, UID)
        VALUES (@userId, @costPerHour, NULL);

        IF @roleIdsCsv IS NOT NULL AND LEN(@roleIdsCsv) > 0
        BEGIN
            INSERT INTO Employee_Roll (employee_user_ID, roll_ID)
            SELECT @userId, RTRIM(LTRIM(Split.a.value('.', 'NVARCHAR(36)')))
            FROM   (SELECT CAST('<X>' + REPLACE(@roleIdsCsv, ',', '</X><X>') + '</X>' AS XML)) AS A(xmlCol)
            CROSS APPLY A.xmlCol.nodes('/X') AS Split(a);
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO


-- =============================================================================
-- Description:  sp_UpdateEmployee
--               Updates User fields, Employee cost, and replaces all role
--               assignments in one transaction.
--               Raises state=2 (→ UnauthorizedAccessException) if employee
--               is not found or belongs to a different company.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_UpdateEmployee
    @userId      NVARCHAR(36),
    @companyId   NVARCHAR(36),
    @firstName   NVARCHAR(100),
    @lastName    NVARCHAR(100),
    @phoneNum    NVARCHAR(50)  = NULL,
    @costPerHour DECIMAL(18,2),
    @roleIdsCsv  NVARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
    BEGIN TRY
        IF NOT EXISTS (
            SELECT 1
            FROM   [User] u
            INNER JOIN Employee e ON u.user_ID = e.user_ID
            WHERE  u.user_ID = @userId AND u.company_ID = @companyId
        )
            RAISERROR('Employee not found or access denied.', 16, 2);

        UPDATE [User]
        SET    firstName = @firstName,
               lastName  = @lastName,
               phoneNum  = @phoneNum
        WHERE  user_ID = @userId;

        UPDATE Employee
        SET    cost_per_hour = @costPerHour
        WHERE  user_ID = @userId;

        DELETE FROM Employee_Roll
        WHERE  employee_user_ID = @userId;

        IF @roleIdsCsv IS NOT NULL AND LEN(@roleIdsCsv) > 0
        BEGIN
            INSERT INTO Employee_Roll (employee_user_ID, roll_ID)
            SELECT @userId, RTRIM(LTRIM(Split.a.value('.', 'NVARCHAR(36)')))
            FROM   (SELECT CAST('<X>' + REPLACE(@roleIdsCsv, ',', '</X><X>') + '</X>' AS XML)) AS A(xmlCol)
            CROSS APPLY A.xmlCol.nodes('/X') AS Split(a);
        END

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO


-- =============================================================================
-- Description:  sp_DeleteEmployee
--               Deletes Employee_Roll → Employee → User in a transaction.
--               Raises state=2 (→ UnauthorizedAccessException) if the employee
--               is not found or belongs to a different company.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_DeleteEmployee
    @userId    NVARCHAR(36),
    @companyId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRANSACTION;
    BEGIN TRY
        IF NOT EXISTS (
            SELECT 1
            FROM   [User] u
            INNER JOIN Employee e ON u.user_ID = e.user_ID
            WHERE  u.user_ID = @userId AND u.company_ID = @companyId
        )
            RAISERROR('Employee not found or access denied.', 16, 2);

        DELETE FROM Brief_Acknowledgment WHERE employee_user_ID = @userId;
        DELETE FROM Employee_Shift        WHERE employee_user_ID = @userId;
        DELETE FROM Employee_Roll         WHERE employee_user_ID = @userId;
        DELETE FROM Employee              WHERE user_ID          = @userId;
        DELETE FROM [User]
        WHERE  user_ID    = @userId
          AND  company_ID = @companyId;

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO


-- =============================================================================
-- DOWN  —  Drop all stored procedures added above.
--          Does NOT drop or alter any tables or data.
--          Uncomment and run to roll back.
-- =============================================================================
/*
DROP PROCEDURE IF EXISTS sp_GetAllRoles;
DROP PROCEDURE IF EXISTS sp_RoleNameExistsForCompany;
DROP PROCEDURE IF EXISTS sp_CreateRole;
DROP PROCEDURE IF EXISTS sp_ValidateRoleIds;
DROP PROCEDURE IF EXISTS sp_EmailExists;
DROP PROCEDURE IF EXISTS sp_GetEmployeesByCompany;
DROP PROCEDURE IF EXISTS sp_GetEmployeeRolesByCompany;
DROP PROCEDURE IF EXISTS sp_GetEmployeeById;
DROP PROCEDURE IF EXISTS sp_GetEmployeeRoles;
DROP PROCEDURE IF EXISTS sp_CreateEmployee;
DROP PROCEDURE IF EXISTS sp_UpdateEmployee;
DROP PROCEDURE IF EXISTS sp_DeleteEmployee;
*/
