-- =============================================================================
-- File:        sp_Projects.sql
-- Project:     Teamgle - Workforce Management Platform
-- Description: Stored Procedures for the Project / Event / Shift module.
--
-- HOW TO USE:
--   UP   section  →  run once to create / update all procedures.
--   DOWN section  →  run to drop all procedures (rollback, at bottom of file).
--
-- NOTE: The repository currently uses inline SQL for create operations.
--       These SPs mirror the exact same logic and can replace them in future.
-- =============================================================================


-- =============================================================================
-- UP  —  Create (or replace) all stored procedures
-- =============================================================================


-- =============================================================================
-- Description:  sp_CreateProject
--               Inserts a new row into Project.
--               GUID is generated by the caller (C# repository).
--               No company_ID on Project — isolation is via Manager_Project.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateProject
    @projId     NVARCHAR(36),
    @name       NVARCHAR(200),
    @startDate  DATE          = NULL,
    @endDate    DATE          = NULL,
    @status     NVARCHAR(50)  = 'draft',
    @customerId NVARCHAR(36)  = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Project
        (Proj_ID, name, start_date, end_date, status, customer_ID)
    VALUES
        (@projId, @name, @startDate, @endDate, @status, @customerId);
END;
GO


-- =============================================================================
-- Description:  sp_CreateManagerProject
--               Links a manager to a project as owner in Manager_Project.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateManagerProject
    @projectId     NVARCHAR(36),
    @managerUserId NVARCHAR(36)
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Manager_Project
        (manager_user_ID, project_ID, is_owner, joined_at)
    VALUES
        (@managerUserId, @projectId, 1, GETDATE());
END;
GO


-- =============================================================================
-- Description:  sp_CreateEvent
--               Inserts a new row into Event and returns the generated event_ID.
--               GUID is generated by the caller (C# repository).
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateEvent
    @eventId         NVARCHAR(36),
    @projectId       NVARCHAR(36),
    @name            NVARCHAR(200),
    @startTime       DATETIME2,
    @endTime         DATETIME2,
    @location        NVARCHAR(300) = NULL,
    @attendeesCount  INT           = NULL,
    @eventType       NVARCHAR(50)  = NULL,
    @plannedBudget   DECIMAL(18,2) = NULL,
    @expectedRevenue DECIMAL(18,2) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Event
        (event_ID, project_ID, name, start_time, end_time,
         location, status, attendees_count, event_type,
         planned_budget, expected_revenue)
    VALUES
        (@eventId, @projectId, @name, @startTime, @endTime,
         @location, 'planning', @attendeesCount, @eventType,
         @plannedBudget, @expectedRevenue);
END;
GO


-- =============================================================================
-- Description:  sp_CreateShift
--               Inserts a new row into Shift.
--               GUID is generated by SQL (NEWID()).
--               start_time / end_time are DATETIME2 — shifts can span days.
-- =============================================================================
CREATE OR ALTER PROCEDURE sp_CreateShift
    @eventId          NVARCHAR(36),
    @rollId           NVARCHAR(36),
    @requiredQuantity INT,
    @startTime        DATETIME2,
    @endTime          DATETIME2
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Shift
        (Shift_ID, event_ID, roll_ID, required_quantity, start_time, end_time)
    VALUES
        (NEWID(), @eventId, @rollId, @requiredQuantity, @startTime, @endTime);
END;
GO


-- =============================================================================
-- DOWN  —  Drop all stored procedures added above.
--          Does NOT drop or alter any tables or data.
--          Uncomment and run to roll back.
-- =============================================================================
/*
DROP PROCEDURE IF EXISTS sp_CreateProject;
DROP PROCEDURE IF EXISTS sp_CreateManagerProject;
DROP PROCEDURE IF EXISTS sp_CreateEvent;
DROP PROCEDURE IF EXISTS sp_CreateShift;
*/
